spring:
  application:
    name: hospital-management-system
  

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:hospital_db}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  

  h2:
    console:
      enabled: true
      path: /h2-console
  

  jpa:
    database-platform: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  

  graphql:
    websocket:
      path: /graphql
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST
      allowed-headers: "*"
  

  security:
    user:
      name: admin
      password: admin123
  

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}
    virtual-host: ${SPRING_RABBITMQ_VIRTUAL_HOST:/}


jwt:
  secret: hospitalManagementSecretKeyForJWTTokenGeneration2024
  expiration: 86400000


server:
  port: 8080
  servlet:
    context-path: /api


logging:
  level:
    com.fiap.atividade3: DEBUG
    org.springframework.security: DEBUG
    org.springframework.graphql: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
