spring:
  application:
    name: hospital-management-system
  
  # Database Configuration (H2 for development)
  datasource:
    url: jdbc:h2:mem:hospital_db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  
  # H2 Console (for development only)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # GraphQL Configuration
  graphql:
    websocket:
      path: /graphql
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql
    cors:
      allowed-origins: "*"
      allowed-methods: GET,POST
      allowed-headers: "*"
  
  # Security Configuration
  security:
    user:
      name: admin
      password: admin123
  
  # RabbitMQ Configuration (disabled for development)
  # rabbitmq:
  #   host: localhost
  #   port: 5672
  #   username: guest
  #   password: guest
  #   virtual-host: /

# JWT Configuration
jwt:
  secret: hospitalManagementSecretKeyForJWTTokenGeneration2024
  expiration: 86400000 # 24 hours in milliseconds

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration
logging:
  level:
    com.fiap.atividade3: DEBUG
    org.springframework.security: DEBUG
    org.springframework.graphql: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
